# This is a GitHub Actions workflow configuration file for Continuous Integration (CI).
# The workflow is triggered on push and pull request events to the main branch.

name: CI  # The name of the workflow

on:
  push:
    branches: [ main ]  # Trigger the workflow on push events to the main branch
  pull_request:
    branches: [ main ]  # Trigger the wor kflow on pull request events to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Step to checkout the repository using the actions/checkout@v2 action

    - name: Set up Python 3.9
      uses: actions/setup-python@v2  # Step to set up Python 3.9 using the actions/setup-python@v2 action
      with:
        python-version: 3.9  # Specify the Python version to be set up

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install the dependencies listed in requirements.txt

    - name: Run tests
      run: pytest tests  # Run the tests using pytest