name: CI

on:
  push:
    branches: [ main ]  # Trigger the workflow on push events to the main branch
  pull_request:
    branches: [ main ]  # Trigger the workflow on pull request events targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the type of runner to use for the job

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Define a matrix of Python versions to test against

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Use the checkout action to clone the repository

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Use the setup-python action to set up the specified Python version
      with:
        python-version: ${{ matrix.python-version }}  # Specify the Python version from the matrix

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2  # Use the setup-miniconda action to install Miniconda
      with:
        python-version: ${{ matrix.python-version }}  # Specify the Python version from the matrix
        auto-update-conda: true  # Automatically update conda to the latest version
        auto-activate-base: false  # Do not auto-activate the base environment

    - name: Create conda environment
      run: conda create --name test-env python=${{ matrix.python-version }} --yes  # Create a new conda environment with the specified Python version

    - name: Activate conda environment
      run: echo "conda activate test-env" >> $GITHUB_ENV  # Activate the conda environment and add it to the GitHub environment variables

    - name: Install dependencies
      run: |
        conda install --file requirements.txt --yes  # Install dependencies from the requirements.txt file
        conda install pytest --yes  # Install pytest for running tests

    - name: Run tests
      run: pytest tests  # Run the tests using pytest